services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: scraper-laravel-app
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./php.ini:/usr/local/etc/php/php.ini
        networks:
            - scraper_network

    worker:
        build:
            context: .
            dockerfile: Dockerfile.worker
        container_name: scraper-laravel-worker
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./php.ini:/usr/local/etc/php/php.ini
        depends_on:
            - app
            - redis
        networks:
            - scraper_network

    nginx:
        image: nginx:latest
        container_name: scraper-nginx
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - ./nginx_default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - scraper_network

    redis:
        image: redis:alpine
        container_name: scraper-redis
        ports:
            - "16379:6379"
        networks:
            - scraper_network

networks:
    scraper_network:
        driver: bridge
